/* Shared identity, preferences and accessible settings for both GSPM views. */
(()=>{'use strict';
const root=document.documentElement,key='gspm.preferences.v1',system=matchMedia('(prefers-reduced-motion: reduce)');
const embedded=new URLSearchParams(location.search).get('embedded')==='1'&&parent!==window;
let saved={};try{const value=JSON.parse(localStorage.getItem(key)||'{}');if(value&&typeof value==='object')saved=value}catch{}
let settings={theme:saved.theme==='light'?'light':'dark',motion:typeof saved.motion==='boolean'?saved.motion:!system.matches};
let explicitMotion=typeof saved.motion==='boolean',view=location.hash==='#eeg'||location.pathname.endsWith('/demo')||location.pathname.includes('eeg_workload')?'eeg':'architecture';
let trigger,panel,backdrop,open=false;
function apply(next,persist=false){settings={theme:next.theme==='light'?'light':'dark',motion:typeof next.motion==='boolean'?next.motion:settings.motion};root.dataset.theme=settings.theme;root.dataset.motion=String(settings.motion);root.classList.add('gspm-ui');if(persist){explicitMotion=true;try{localStorage.setItem(key,JSON.stringify(settings))}catch{}}
sync();window.dispatchEvent(new CustomEvent('gspm:preferenceschange',{detail:{...settings}}));}
function sync(){if(!panel)return;panel.querySelectorAll('[data-page]').forEach(b=>{b.setAttribute('aria-current',b.dataset.page===view?'page':'false');b.querySelector('.selected-mark').textContent=b.dataset.page===view?'✓':''});panel.querySelectorAll('[data-theme-choice]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.themeChoice===settings.theme)));const toggle=panel.querySelector('[data-motion-toggle]');toggle.setAttribute('aria-checked',String(settings.motion));toggle.querySelector('.switch-label').textContent=settings.motion?'开启':'关闭';}
function close(focus=true){if(!open)return;open=false;panel.hidden=true;if(backdrop)backdrop.hidden=true;trigger.setAttribute('aria-expanded','false');if(focus)trigger.focus();}
function mount(){if(embedded)return;let header=document.querySelector('.gspm-header');if(!header){header=document.createElement('header');header.className='gspm-header';document.body.prepend(header)}
header.innerHTML=`<a class="gspm-brand" href="${location.protocol==='file:'?'gspm_network_atlas.html':'portal.html#architecture'}" aria-label="思维轨迹 首页"><img src="assets/brand/team-logo.png" width="36" height="36" alt="思维轨迹"><span>思维轨迹</span></a><div class="gspm-settings"><button class="settings-trigger" type="button" aria-label="打开平台设置" aria-expanded="false" aria-controls="gspm-settings-panel"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="7" r="3"/><path d="M5 20v-2a7 7 0 0 1 14 0v2"/></svg></button><div class="settings-panel" id="gspm-settings-panel" role="dialog" aria-label="平台设置" hidden><p class="settings-caption">页面</p><button data-page="architecture" type="button">网络原理<span class="selected-mark"></span></button><button data-page="eeg" type="button">EEG 分类<span class="selected-mark"></span></button><div class="settings-divider"></div><div class="settings-row"><span>动效</span><button type="button" role="switch" aria-label="开启动效" data-motion-toggle><span class="switch-track"><i></i></span><span class="switch-label"></span></button></div><div class="settings-row"><span>主题</span><div class="theme-options"><button type="button" data-theme-choice="dark">深色</button><button type="button" data-theme-choice="light">浅色</button></div></div></div></div>`;
trigger=header.querySelector('.settings-trigger');panel=header.querySelector('.settings-panel');backdrop=document.createElement('div');backdrop.className='settings-backdrop';backdrop.hidden=true;backdrop.setAttribute('aria-hidden','true');document.body.append(backdrop);backdrop.addEventListener('pointerdown',()=>close());trigger.onclick=()=>{if(open){close();return}open=true;panel.hidden=false;backdrop.hidden=false;trigger.setAttribute('aria-expanded','true');panel.querySelector('[data-page]').focus()};
panel.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{const target=b.dataset.page;close();if(document.body.classList.contains('portal-body'))window.dispatchEvent(new CustomEvent('gspm:navigationrequest',{detail:{view:target}}));else location.href=location.protocol==='file:'?(target==='eeg'?'gspm_eeg_workload_demo.html':'gspm_network_atlas.html'):'portal.html#'+target;});
panel.querySelector('[data-motion-toggle]').onclick=()=>apply({...settings,motion:!settings.motion},true);panel.querySelectorAll('[data-theme-choice]').forEach(b=>b.onclick=()=>apply({...settings,theme:b.dataset.themeChoice},true));
document.addEventListener('pointerdown',e=>{if(open&&!header.querySelector('.gspm-settings').contains(e.target))close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&open){e.preventDefault();e.stopPropagation();close()}},true);
if(!document.querySelector('.gspm-footer')){const footer=document.createElement('footer');footer.className='gspm-footer';footer.textContent='思维轨迹出品';document.body.append(footer)}sync();}
window.GSPMUI={get settings(){return {...settings}},setPreferences:apply,setView(value){view=value;sync()}};
apply(settings);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
window.addEventListener('message',e=>{if(!embedded||e.source!==parent||e.origin!==location.origin||e.data?.type!=='gspm:preferences'||!['dark','light'].includes(e.data.theme)||typeof e.data.motion!=='boolean')return;apply(e.data)});
window.addEventListener('storage',e=>{if(e.key!==key)return;try{const value=JSON.parse(e.newValue||'{}');if(['dark','light'].includes(value.theme)&&typeof value.motion==='boolean'){explicitMotion=true;apply(value)}}catch{}});
system.addEventListener('change',e=>{if(!embedded&&!explicitMotion)apply({...settings,motion:!e.matches})});
})();
