import {lazy,Suspense,useEffect,useState} from 'react';
import {Activity,Box,Layers3,MoveUpRight,Play,Pause,RotateCcw,ScanLine,ChevronRight,ChevronDown,FlaskConical,Expand,Minimize2,ExternalLink,GitBranch,BookOpen,ShieldCheck} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Slider} from '@/components/ui/slider';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Switch} from '@/components/ui/switch';
import {modules,inferenceKeys,trainKeys,innerKeys,type ModuleKey} from './data';
import Lab from './Lab';
import {api,type Status} from './api';
const NetworkScene=lazy(()=>import('./Scene'));

export function useReducedMotion(){const [reduced,setReduced]=useState(false);useEffect(()=>{const mq=window.matchMedia('(prefers-reduced-motion: reduce)');setReduced(mq.matches);const fn=()=>setReduced(mq.matches);mq.addEventListener('change',fn);return()=>mq.removeEventListener('change',fn)},[]);return reduced}
function Header({lab,status}:{lab:boolean,status:Status|null}){return <header className="site-header"><a className="brand" href="/" aria-label="GSPM-Net 首页"><span className="brand-mark"><Activity size={22}/></span><strong>GSPM<span>—</span>Net</strong><span className="brand-sub">RESEARCH / 01</span></a><nav aria-label="主导航"><a className={!lab?'active':''} href="/">网络探索</a><a className={lab?'active':''} href="/lab">EEG 分析</a><a className="research-link" href="/architecture.html">架构图解</a></nav><span className="local-label"><ShieldCheck size={14}/> 本机工作台</span></header>}

function Explorer(){const [selected,setSelected]=useState<ModuleKey>('gsc');const [explode,setExplode]=useState(.8);const [mode,setMode]=useState<'train'|'inference'>('inference');const [inside,setInside]=useState(false);const [playing,setPlaying]=useState(false);const [reset,setReset]=useState(0);const [flat,setFlat]=useState(false);const reduced=useReducedMotion();const m=modules[selected];const keys=inside?innerKeys:mode==='train'?trainKeys:inferenceKeys;
 const selectMode=(value:string)=>{setMode(value as 'train'|'inference');setInside(false);setSelected('gsc')};
 return <section className="explorer section-wrap" id="network"><div className="section-heading"><div><p className="eyebrow">01 / EXPLORE THE ARCHITECTURE</p><h2>将网络展开，<span>看见每一步。</span></h2></div><p>从 62 通道脑电到工作负荷状态。<br/>选择一个模块，沿着数据流理解它的作用。</p></div>
 <div className="explorer-shell"><div className="explorer-top"><Tabs value={mode} onValueChange={selectMode}><TabsList><TabsTrigger value="inference">目标推理</TabsTrigger><TabsTrigger value="train">自监督预训练</TabsTrigger></TabsList></Tabs><div className="scene-view-switch"><Switch id="flat-view" checked={flat} onCheckedChange={setFlat}/><label htmlFor="flat-view">二维视图</label></div></div>
 <div className="explorer-main"><div className="scene-column"><div className="scene-caption"><span>{inside?'GSC / 内部结构':mode==='train'?'MATB-II / 无标签预训练':'N-BACK / 冻结编码器推理'}</span><span>结构示意 · 非实时激活</span></div>
 <div className="network-canvas" aria-label="可旋转的网络三维结构"><Suspense fallback={<div className="scene-loading">正在加载结构视图…</div>}>{flat?<div className="flat-network"><p>选择模块查看结构和说明</p><div>{keys.map((id,i)=><button className={selected===id?'active':''} key={id} onClick={()=>setSelected(id)}><span>0{i+1}</span><strong>{modules[id].title}</strong><small>{modules[id].output}</small></button>)}</div></div>:<NetworkScene explode={explode} mode={mode} inside={inside} selected={selected} onSelect={setSelected} playing={playing} reset={reset} reduced={reduced}/>}</Suspense></div>
 <div className="scene-hint"><span>拖动旋转 · 滚轮缩放</span><span>{reduced?'已遵循系统减少动态效果设置':'点击模块查看详情'}</span></div>
 <div className="scene-controls"><Button variant="outline" onClick={()=>setExplode(explode>.5?0:1)}>{explode>.5?<Minimize2 size={16}/>:<Expand size={16}/>} {explode>.5?'合拢网络':'拆解网络'}</Button><div className="spread-control"><span>展开</span><Slider aria-label="网络展开程度" value={[explode*100]} onValueChange={v=>setExplode(v[0]/100)} min={0} max={100} step={1}/><span>{Math.round(explode*100)}%</span></div><Button variant="ghost" size="icon" aria-label="复位视角" title="复位视角" onClick={()=>setReset(v=>v+1)}><RotateCcw size={17}/></Button><Button variant="outline" disabled={reduced} onClick={()=>setPlaying(v=>!v)}>{playing?<Pause size={15}/>:<Play size={15}/>} {playing?'暂停':'播放数据流'}</Button></div></div>
 <aside className="module-panel" aria-live="polite"><div className="module-index"><span style={{background:m.color}}/> MODULE / {String(keys.indexOf(selected)+1).padStart(2,'0')}</div><h3>{m.title}</h3><p className="module-en">{m.en}</p><p className="module-summary">{m.summary}</p><div className="io-line"><span>INPUT</span><strong>{m.input}</strong></div><div className="io-line"><span>OUTPUT</span><strong>{m.output}</strong></div><p className="module-detail">{m.detail}</p><div className="source-ref"><GitBranch size={14}/><code>{m.code}</code></div><Button className="inside-btn" variant="outline" onClick={()=>{setInside(v=>!v);setSelected(inside?'gsc':'band');setExplode(1)}}><Layers3 size={16}/>{inside?'返回完整网络':'深入 GSC 编码器'}</Button></aside></div>
 <div className="module-tabs" aria-label="键盘可操作的模块选择">{keys.map((id,i)=><button key={id} aria-pressed={selected===id} className={selected===id?'active':''} onClick={()=>setSelected(id)}><span>{String(i+1).padStart(2,'0')}</span>{modules[id].title}</button>)}</div></div>
 </section>
}

function Home(){const [heroReady,setHeroReady]=useState(false);const reduced=useReducedMotion();useEffect(()=>setHeroReady(true),[]);return <>
 <section className="hero section-wrap"><div className="hero-copy"><p className="eyebrow"><span className="tiny-line"/> EEG INTELLIGENCE / GSPM-NET</p><h1>从脑电，<br/>读懂<span>认知负荷。</span></h1><p className="hero-description">跨任务学习脑电表示，用少量个人样本完成适配。<br className="desktop-br"/> 将频谱、空间与时间的信息，汇成稳定的判断。</p><div className="hero-actions"><Button asChild size="lg"><a href="#network"><Box size={18}/> 探索网络结构</a></Button><Button asChild variant="outline" size="lg"><a href="/lab"><ScanLine size={18}/> 进入 EEG 分析</a></Button></div><div className="hero-footnote"><span>MATB-II → N-back</span><span>Self-supervised · Few-shot · Causal</span></div></div>
 <div className="hero-visual" aria-label="网络模块示意"><div className="hero-orbit-label"><span>GATED SPECTRAL–CHANNEL</span><span className="mono">5 × 62 → 96</span></div><div className="hero-canvas">{heroReady&&<Suspense fallback={null}><NetworkScene explode={.52} mode="inference" inside={false} selected="gsc" onSelect={()=>document.getElementById('network')?.scrollIntoView({behavior:reduced?'instant':'smooth'})} playing={false} reset={0} reduced={reduced}/></Suspense>}</div><div className="hero-bottom-label"><span>频带 × 通道 × 时间</span><span>01 — 05</span></div></div></section>
 <div className="metrics-strip section-wrap"><div><strong>87.72<span>%</span></strong><p>平均准确率 <small>± 11.03%</small></p></div><div><strong>26<span>名</span></strong><p>被试独立评估</p></div><div><strong>20<span>个 / 类</span></strong><p>目标标注窗口总量</p></div><div className="metrics-note"><BookOpen size={19}/><p>论文报告的 26 折结果。<br/>非本工作台新增测试成绩。</p></div></div>
 <Explorer/>
 <section className="method-section section-wrap" id="method"><div className="section-heading"><div><p className="eyebrow">02 / HOW IT LEARNS</p><h2>三个阶段，<span>各有所长。</span></h2></div><p>先学习通用表示，再建立个人标准，<br/>最后借助时间信息稳定决策。</p></div><div className="method-grid">{[{n:'01',icon:<Layers3/>,title:'从无标签数据学习',sub:'REPRESENTATION',text:'在源被试的 MATB-II 数据上，联合掩码重建与 VICReg 学习频谱结构。预训练不接触 N-back 记录和工作负荷标签。',tag:'重建 + VICReg'},{n:'02',icon:<ScanLine/>,title:'适应新的个体',sub:'PERSONALIZATION',text:'冻结编码器，以新用户少量已标注样本建立标准化参数与高斯原型。查询窗口分类后，再缓慢更新对应原型。',tag:'96 维特征 · 无梯度微调'},{n:'03',icon:<Activity/>,title:'让判断保持连贯',sub:'STABILIZATION',text:'EMA 与 Markov 综合已经观察到的概率，减少短窗口跳变。时序参数由独立验证被试选择，在目标评估前固定。',tag:'只使用当前与过去'}].map(x=><article key={x.n}><div className="method-card-top"><span>{x.n}</span>{x.icon}</div><p className="eyebrow">{x.sub}</p><h3>{x.title}</h3><p>{x.text}</p><span className="method-tag">{x.tag}</span></article>)}</div></section>
 <section className="evidence-section section-wrap" id="evidence"><div className="section-heading"><div><p className="eyebrow">03 / RESEARCH EVIDENCE</p><h2>每一项设计，<span>都有实验回应。</span></h2></div><span className="source-pill">来源 / 原版论文 · COG-BCI</span></div><div className="evidence-grid"><article className="evidence-card"><div><p className="eyebrow">SUPPORT SIZE</p><h3>有限标注，也能建立个人标准。</h3><p>每类 20 个窗口时达到 87.72%，增加至 30 个时为 89.13%。论文将每类 20 个窗口按 7 / 7 / 6 分配到三个 session。</p></div><figure><img src="/research/Kshot_sensitivity.png" alt="支持集从每类3个增长到30个时的准确率变化，20个时为87.72%"/><figcaption>误差棒：26 名被试之间的标准差。</figcaption></figure></article><article className="evidence-card"><div><p className="eyebrow">TEMPORAL CONSISTENCY</p><h3>时间信息，让短窗输出更稳定。</h3><p>单窗口准确率 76.65%，完整时序处理后 87.72%。每条任务记录内只有一种标签，结果主要支持决策稳定性。</p></div><figure><img src="/research/Temporal_strategy_comparison.png" alt="单窗口、累计平均、首窗保持和因果Markov策略的对比"/><figcaption>相对累计平均的差异未达统计显著。</figcaption></figure></article></div>
 <details className="research-details"><summary>更多实验与研究边界 <ChevronDown size={18}/></summary><div className="detail-research-grid"><div><h3>同输入编码器比较</h3><table><thead><tr><th>编码器</th><th>准确率</th></tr></thead><tbody>{[['GSC','87.72%'],['EEGNeX','83.47%'],['TSNN','83.37%'],['EEGNet','81.01%'],['EEG-Conformer','80.23%']].map(r=><tr key={r[0]}><td>{r[0]}</td><td>{r[1]}</td></tr>)}</tbody></table><p>所有模型适配为相同 5 × 62 log-PSD 输入，使用相同下游协议；不是原始完整方案的直接排名。</p></div><div><h3>自监督与结构消融</h3><p>重建 + VICReg：87.72%；仅重建：85.41%；仅 VICReg：81.58%。去掉原始 PSD 直连后：77.44%。</p><img src="/research/SSL_objective_comparison.png" alt="自监督训练目标比较"/></div></div><div className="boundary-note"><ShieldCheck size={20}/><p>当前研究验证 0-back / 2-back 二分类。连续负荷切换、多设备泛化和完整实时采集链路尚待验证。SHAP 解释模型依赖的特征，不直接证明神经生理因果机制。</p></div></details></section>
 <section className="lab-cta section-wrap"><div><p className="eyebrow">04 / LOCAL ANALYSIS</p><h2>把网络，交给你的脑电。</h2><p>导入记录、完成个人校准、查看逐窗结果。数据始终留在本机。</p></div><Button asChild size="lg"><a href="/lab"><FlaskConical size={18}/> 打开分析工作台</a></Button></section>
 </>}

export default function App(){const lab=window.location.pathname.startsWith('/lab');const [status,setStatus]=useState<Status|null>(null);useEffect(()=>{api<Status>('/status').then(setStatus).catch(()=>{})},[]);return <><a className="skip-link" href="#main">跳到主要内容</a><Header lab={lab} status={status}/><main id="main">{lab?<Lab status={status} onStatus={setStatus}/>:<Home/>}</main><footer className="site-footer section-wrap"><a href="/" className="footer-brand"><Activity size={18}/> GSPM-Net</a><span>跨任务自监督脑电工作负荷识别</span><span>本地研究工作台 · 2026</span></footer></>}
