export type ModuleKey = 'signal'|'psd'|'gsc'|'prototype'|'temporal'|'mask'|'reconstruction'|'vicreg'|'band'|'channel'|'joint'|'rank'|'residual'|'skip'|'feature';
export const modules: Record<ModuleKey,{title:string,en:string,color:string,input:string,output:string,summary:string,detail:string,code:string}> = {
  signal:{title:'信号预处理',en:'EEG INPUT',color:'#8ca9c5',input:'62 通道原始 EEG',output:'250 Hz · 2 秒窗口',summary:'让不同记录进入同一信号空间。',detail:'处理坏通道，执行 50 Hz 陷波、1–40 Hz 带通、稳健限幅与平均重参考，再重采样至 250 Hz。现有研究使用离线双向滤波。',code:'signal.py · preprocess'},
  psd:{title:'频谱表示',en:'SPECTRAL MAP',color:'#70c7db',input:'62 × 500 个采样值',output:'5 × 62 log-PSD',summary:'把波形转为频带与空间的二维描述。',detail:'用 1 秒 Hann 窗、50% 重叠的 Welch 估计功率谱，汇总 θ、α、低 β、高 β、γ 五频带并取对数。5 × 62 共 310 个数值保留频带和电极结构。',code:'signal.py · welch_features'},
  gsc:{title:'GSC 编码器',en:'GATED ENCODER',color:'#85e5c6',input:'5 × 62 标准化频谱',output:'96 维特征向量',summary:'在频带、通道及其交互中寻找有效表示。',detail:'三类门控、低秩交互与残差融合共同提取特征。原始 PSD 通过直连分支保留。目标分析时编码器被冻结，点击“深入 GSC”可以拆解内部结构。',code:'network.py · EnhancedGatedSpectralChannelNet'},
  prototype:{title:'高斯原型适配',en:'GAUSSIAN PROTOTYPES',color:'#b5c7f1',input:'96 维特征 + 两类支持集',output:'P(0-back) · P(2-back)',summary:'用少量个人样本建立自己的判断标准。',detail:'支持集估计两类特征均值与收缩方差。新窗口按高斯得分分类，然后使用伪标签更新预测类原型。编码器不做梯度微调，查询真值不参与更新。',code:'engine.py · calibrate / predict'},
  temporal:{title:'因果时序决策',en:'TEMPORAL STATE',color:'#d8ceac',input:'逐窗类别概率',output:'0-back / 2-back 状态',summary:'整合已经观察到的信息，减少预测抖动。',detail:'先用 EMA 平滑概率，再以两状态 Markov 递推与滞回阈值稳定输出。仅使用当前与过去窗口；参数应来自独立验证被试。它不证明完整实时采集链路已获验证。',code:'engine.py · temporal_decision'},
  mask:{title:'生成两种扰动视图',en:'PAIRED VIEWS',color:'#89aec2',input:'MATB-II 频谱特征',output:'独立遮挡的视图 X₁ / X₂',summary:'从同一份数据构造两道不同的学习题。',detail:'随机遮挡元素、整个频带或通道，并叠加轻微幅度变化和噪声。两种视图由共享 GSC 编码器处理，无需工作负荷标签。',code:'研究代码 · make_masked_view'},
  reconstruction:{title:'掩码重建',en:'RECONSTRUCTION',color:'#a6d5e0',input:'96 维编码特征',output:'被遮挡位置的重建误差',summary:'通过恢复缺失信息，学习频谱结构。',detail:'轻量解码器恢复原始频谱，损失只在遮挡位置计算。该分支只在源任务自监督训练时使用，目标推理时被移除。',code:'研究代码 · SSLGatedModel / ssl_batch_loss'},
  vicreg:{title:'VICReg 正则化',en:'VICREG',color:'#bfb8de',input:'两种视图的投影特征',output:'一致性 + 方差 + 协方差损失',summary:'保持同一样本的一致性，避免特征坍缩。',detail:'让成对表示相近、保留样本间变化、减少特征维度冗余。联合目标权重为：重建 1、一致性 5、方差 1、协方差 0.05。预训练结束只保留编码器。',code:'研究代码 · vicreg_loss'},
  band:{title:'频带门控',en:'BAND GATE',color:'#70c7db',input:'各频带均值 / 标准差',output:'5 个频带权重',summary:'当前样本中，哪些频带更值得关注？',detail:'依据跨通道的频带统计量生成 Tanh 门控，对频带维度连续加权；不是简单删除频带。',code:'network.py · band_gate'},
  channel:{title:'通道门控',en:'CHANNEL GATE',color:'#93bddc',input:'各通道均值 / 标准差',output:'62 个通道权重',summary:'当前样本中，哪些电极位置更有信息？',detail:'依据跨频带统计描述生成通道门控，与频带权重共同构成可分离调制。',code:'network.py · channel_gate'},
  joint:{title:'联合门控',en:'JOINT GATE',color:'#85e5c6',input:'310 维展开频谱',output:'5 × 62 联合权重',summary:'进一步关注特定电极上的特定频带。',detail:'每个频带与通道的组合都获得独立的调制权重，补充仅按整行或整列加权无法表达的关系。',code:'network.py · band_channel_gate'},
  rank:{title:'低秩交互',en:'LOW-RANK',color:'#abd5b7',input:'频带参数 U · 通道参数 V',output:'低秩调制与统计特征',summary:'以较少参数表示频带和通道的结构关系。',detail:'可学习的低秩矩阵产生额外的结构调制；rank=16。该信息与原始、门控及统计特征一同输入融合网络。',code:'network.py · low_rank_band / low_rank_channel'},
  residual:{title:'残差融合',en:'RESIDUAL FUSION',color:'#b5c7f1',input:'拼接后的增强表示',output:'96 维融合特征',summary:'将多种观察角度融合成统一表示。',detail:'通过 LayerNorm、全连接映射、GELU 与 3 个残差块进行特征整合。残差连接保留信息传递路径。',code:'network.py · encoder / ResidualDenseBlock'},
  skip:{title:'原始 PSD 直连',en:'RAW SKIP',color:'#d8ceac',input:'310 维原始频谱',output:'96 维直连特征',summary:'让原始信息在学习的变换之外保留下来。',detail:'原始频谱经过独立映射，以可学习系数加入融合表示。论文中去掉这一分支后平均准确率降至 77.44%。',code:'network.py · raw_skip / skip_alpha'},
  feature:{title:'最终特征',en:'EMBEDDING',color:'#85e5c6',input:'残差融合 + 原始直连',output:'96 维向量',summary:'统一表示交给训练头或原型分类器。',detail:'预训练时特征用于重建和 VICReg；目标推理时特征与高斯原型匹配。展示的是结构关系，不是实时激活值。',code:'network.py · forward(return_features=True)'},
};
export const inferenceKeys:ModuleKey[]=['signal','psd','gsc','prototype','temporal'];
export const trainKeys:ModuleKey[]=['psd','mask','gsc','reconstruction','vicreg'];
export const innerKeys:ModuleKey[]=['band','channel','joint','rank','residual','skip','feature'];
export type ResultRow={window:number,start_sec:number,end_sec:number,prob_0:number,prob_2:number,raw_class:number,state_prob_0:number,state_prob_2:number,class_label:number};
export type Result={id:string,status:string,progress:number,mode:'demo'|'real',rows?:ResultRow[],windows?:number,duration_sec?:number,high_ratio?:number,switches?:number,temporal_enabled?:boolean,error?:string,recording_name?:string,created_at?:number,model_version?:string,audit?:{window_mode:string,discarded_tail_sec:number,bad_channels_repaired:string[]},psd?:number[][]};
export const demoWave=Array.from({length:600},(_,i)=>{const t=i*.1;return {t,Fp1:Math.sin(t*4.8)*12+Math.sin(t*14.7)*6,Fz:Math.sin(t*5.3+.5)*15+Math.sin(t*23)*3,C3:Math.sin(t*3.9+1)*9+Math.sin(t*21)*5,Pz:Math.sin(t*6.3+2)*11+Math.sin(t*12)*7,O1:Math.sin(t*5.9+4)*10+Math.sin(t*20)*3}});
export function demoResult():Result {const rows=Array.from({length:30},(_,i)=>{const high=i>=10&&i<23;const p2=(high?.68:.27)+Math.sin(i*1.7)*.16;const state=high?.83+Math.sin(i)*.04:.18+Math.sin(i)*.04;return {window:i+1,start_sec:i*2,end_sec:i*2+2,prob_0:1-p2,prob_2:p2,raw_class:p2>.5?2:0,state_prob_0:1-state,state_prob_2:state,class_label:high?2:0}});return {id:'demo',status:'complete',progress:100,mode:'demo',rows,windows:30,duration_sec:60,high_ratio:13/30,switches:2,temporal_enabled:true,recording_name:'合成演示信号 · 非模型预测'};}
