import {useEffect,useRef,useState,type ReactNode} from 'react';
import {Activity,AlertCircle,Check,ChevronLeft,ChevronRight,Download,FileUp,FlaskConical,LoaderCircle,Play,RefreshCw,ShieldCheck,Trash2,Upload,Waves,Layers3,Database,Plus,Info} from 'lucide-react';
import {Line,LineChart,XAxis,YAxis,CartesianGrid,Tooltip} from 'recharts';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Progress} from '@/components/ui/progress';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {AlertDialog,AlertDialogAction,AlertDialogCancel,AlertDialogContent,AlertDialogDescription,AlertDialogFooter,AlertDialogHeader,AlertDialogTitle} from '@/components/ui/alert-dialog';
import {ChartContainer} from '@/components/ui/chart';
import {api,post,type Recording,type Profile,type Status} from './api';
import {demoResult,demoWave,type Result} from './data';

function Choice({value,onChange,options,placeholder='请选择',id,disabled=false}:{value:string,onChange:(v:string)=>void,options:{value:string,label:string}[],placeholder?:string,id?:string,disabled?:boolean}){return <Select value={value} onValueChange={onChange} disabled={disabled}><SelectTrigger id={id} className="form-select"><SelectValue placeholder={placeholder}/></SelectTrigger><SelectContent>{options.map(x=><SelectItem key={x.value} value={x.value}>{x.label}</SelectItem>)}</SelectContent></Select>}
function Field({label,id,children}:{label:string,id:string,children:ReactNode}){return <div className="form-field"><Label htmlFor={id}>{label}</Label>{children}</div>}
function downloadDemo(result:Result,format:'csv'|'json'){
 const rows=result.rows||[];let content:string;
 if(format==='json')content=JSON.stringify({...result,notice:'合成信号与预设演示结果，不是模型真实预测。'},null,2);
 else {const keys=Object.keys(rows[0]||{});content='\ufeffmode,'+keys.join(',')+'\n'+rows.map(r=>'DEMO,'+keys.map(k=>(r as any)[k]).join(',')).join('\n')}
 const url=URL.createObjectURL(new Blob([content],{type:format==='csv'?'text/csv':'application/json'}));const a=document.createElement('a');a.href=url;a.download=`GSPM-DEMO.${format}`;a.click();URL.revokeObjectURL(url);
}
function SignalChart({data}:{data:any[]}){const colors=['#84e4c6','#83b8dc','#b9b2e2','#dcc399','#889ca9'];return <ChartContainer config={Object.fromEntries(['Fp1','Fz','C3','Pz','O1'].map((x,i)=>[x,{label:x,color:colors[i]}]))} className="wave-chart"><LineChart data={data} margin={{top:10,right:10,left:0,bottom:0}}><CartesianGrid stroke="#253038" vertical={false}/><XAxis dataKey="t" tickFormatter={v=>`${Math.round(v)}s`} minTickGap={60} stroke="#6d7b85"/><YAxis hide domain={['auto','auto']}/><Tooltip contentStyle={{background:'#192127',border:'1px solid #394952',borderRadius:8}} labelFormatter={v=>`${Number(v).toFixed(2)} 秒`}/>{['Fp1','Fz','C3','Pz','O1'].map((x,i)=><Line key={x} name={x} dataKey={(p:any)=>(p[x]||0)+(2-i)*35} type="linear" stroke={colors[i]} dot={false} strokeWidth={1.2} isAnimationActive={false}/>)}</LineChart></ChartContainer>}

export default function Lab({status,onStatus}:{status:Status|null,onStatus:(v:Status)=>void}){
 const [mode,setMode]=useState<'demo'|'real'>('demo');const [records,setRecords]=useState<Recording[]>([]);const [profiles,setProfiles]=useState<Profile[]>([]);const [history,setHistory]=useState<Result[]>([]);const [files,setFiles]=useState<File[]>([]);const [sfreq,setSfreq]=useState('500');const [unit,setUnit]=useState('uV');const [onsets,setOnsets]=useState('');const [query,setQuery]=useState('');const [current,setCurrent]=useState<Recording|null>(null);const [modelId,setModelId]=useState('');const [record0,setRecord0]=useState('');const [record2,setRecord2]=useState('');const [subject,setSubject]=useState('用户 01');const [session,setSession]=useState('Session 01');const [shots,setShots]=useState('20');const [windowMode,setWindowMode]=useState<'continuous'|'events'>('continuous');const [eventTypes,setEventTypes]=useState('');const [profile,setProfile]=useState('');const [showCalibration,setShowCalibration]=useState(false);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [message,setMessage]=useState('');const [result,setResult]=useState<Result|null>(null);const [page,setPage]=useState(0);const [deleteTarget,setDeleteTarget]=useState<{kind:string,id:string,label:string}|null>(null);const [drag,setDrag]=useState(false);const uploadRef=useRef<HTMLInputElement>(null);const previewRequest=useRef(0);const demoTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const refresh=async()=>{try{const [s,r,p,h]=await Promise.all([api<Status>('/status'),api<Recording[]>('/recordings'),api<Profile[]>('/calibrations'),api<Result[]>('/analyses')]);onStatus(s);setRecords(r);setProfiles(p);setHistory(h)}catch(e){setError((e as Error).message)}};
 useEffect(()=>{void refresh();return()=>{if(demoTimer.current)clearTimeout(demoTimer.current)}},[]);
 useEffect(()=>{const id=++previewRequest.current;if(query){api<Recording>(`/recordings/${query}`).then(v=>{if(id===previewRequest.current)setCurrent(v)}).catch(e=>setError(e.message))}else setCurrent(null)},[query]);
 useEffect(()=>{if(!result||mode!=='real'||!['queued','running'].includes(result.status))return;let alive=true;const timer=setInterval(()=>{api<Result>(`/analyses/${result.id}`).then(v=>{if(!alive)return;setResult(v);if(v.status==='complete'||v.status==='failed'){setBusy('');if(v.error)setError(v.error);void refresh()}}).catch(e=>{if(alive){setError(e.message);setBusy('')}})},900);return()=>{alive=false;clearInterval(timer)}},[result?.id,result?.status,mode]);
 const recOptions=records.map(r=>({value:r.id,label:`${r.name} · ${r.duration_sec.toFixed(1)}s`}));
 const profileOptions=profiles.map(p=>({value:p.id,label:`${p.subject} / ${p.session} · ${p.shots}个/类`}));
 const switchMode=(v:string)=>{if(busy)return;setMode(v as any);setResult(null);setPage(0);setError('');setMessage('')};
 const chooseProfile=(id:string)=>{setProfile(id);setResult(null);const p=profiles.find(x=>x.id===id);if(p){setModelId(p.model_id||'');setSubject(p.subject);setSession(p.session);setWindowMode(p.window_mode);setEventTypes(p.event_types.join(','))}};
 const upload=async()=>{if(!files.length)return;setBusy('upload');setError('');setMessage('');try{const data=new FormData();files.forEach(f=>data.append('files',f));if(sfreq)data.append('sfreq',sfreq);data.append('unit',unit);if(onsets.trim())data.append('event_onsets',onsets);const r=await api<Recording>('/recordings',{method:'POST',body:data});setQuery(r.id);setCurrent(r);setFiles([]);if(uploadRef.current)uploadRef.current.value='';setMessage(`已导入 ${r.name}，62 通道检查通过。`);setResult(null);await refresh()}catch(e){setError((e as Error).message)}finally{setBusy('')}};
 const createCalibration=async()=>{setBusy('calibration');setError('');try{const p=await post('/calibrations',{record_0:record0,record_2:record2,model_id:modelId||null,subject,session,shots:Number(shots),window_mode:windowMode,event_types:eventTypes.split(',').map(v=>v.trim()).filter(Boolean)});setProfile(p.id);setMessage('个人校准档案已建立。请使用独立查询记录进行分析。');setShowCalibration(false);await refresh()}catch(e){setError((e as Error).message)}finally{setBusy('')}};
 const run=async()=>{setError('');setMessage('');setPage(0);if(mode==='demo'){setBusy('demo');setResult({id:'demo',mode:'demo',status:'running',progress:35});demoTimer.current=setTimeout(()=>{setResult(demoResult());setBusy('')},1000);return}setBusy('analysis');try{const job=await post('/analyses',{recording_id:query,calibration_id:profile,subject,session,window_mode:windowMode,event_types:eventTypes.split(',').map(v=>v.trim()).filter(Boolean)});setResult(job)}catch(e){setError((e as Error).message);setBusy('')}};
 const performDelete=async()=>{if(!deleteTarget)return;try{await api(`/${deleteTarget.kind}/${deleteTarget.id}`,{method:'DELETE'});if(deleteTarget.kind==='recordings'&&query===deleteTarget.id){setQuery('');setCurrent(null)}if(deleteTarget.kind==='calibrations'&&profile===deleteTarget.id)setProfile('');if(deleteTarget.kind==='analyses'&&result?.id===deleteTarget.id)setResult(null);setMessage('本机记录已删除。');await refresh()}catch(e){setError((e as Error).message)}finally{setDeleteTarget(null)}};
 const selectedProfile=profiles.find(p=>p.id===profile);const selectedFold=status?.model.folds?.find(f=>f.id===selectedProfile?.model_id);
 const ready=mode==='demo'||(status?.model.ready&&profile&&query&&subject.trim()&&session.trim()&&(!selectedProfile?.model_id||selectedFold?.ready));
 const done=result?.status==='complete';
 return <div className="lab-page section-wrap"><div className="lab-heading"><div><p className="eyebrow">EEG / LOCAL WORKBENCH</p><h1>脑电分析工作台<span>。</span></h1><p>从一段信号开始，观察频谱与认知负荷。</p></div><div className="lab-heading-actions"><span className={`model-badge ${status?.model.ready?'ready':''}`}><span/>{status?.model.ready?status.model.mode==='folds'?`${status.model.folds?.filter(x=>x.ready).length} 折模型就绪`:'模型已就绪':'等待接入模型'}</span><Button variant="ghost" size="icon" aria-label="刷新本地状态" title="刷新本地状态" onClick={()=>void refresh()}><RefreshCw size={17}/></Button></div></div>
 <div className="lab-mode-bar"><Tabs value={mode} onValueChange={switchMode}><TabsList><TabsTrigger value="demo" disabled={!!busy}><FlaskConical size={15}/> 演示体验</TabsTrigger><TabsTrigger value="real" disabled={!!busy}><Database size={15}/> 本地 EEG</TabsTrigger></TabsList></Tabs><span><ShieldCheck size={15}/>{mode==='demo'?'合成信号 · 预设结果 · 非真实推理':'数据只保存在本机，不向外部上传'}</span></div>
 {error&&<div className="notice error" role="alert"><AlertCircle size={18}/><p>{error}</p><button aria-label="关闭错误提示" onClick={()=>setError('')}>×</button></div>}{message&&<div className="notice success" role="status"><Check size={18}/><p>{message}</p></div>}
 <div className="workbench-grid"><aside className="lab-sidebar">
 <section className="lab-card"><div className="card-heading"><h2><span>01</span> 信号输入</h2>{mode==='demo'&&<span className="demo-chip">DEMO</span>}</div>{mode==='demo'?<><div className="demo-file"><div className="file-icon"><Waves size={28}/></div><strong>示例脑电信号</strong><p>确定性合成波形，用于体验操作与可视化。</p><div><span>62 通道</span><span>250 Hz</span><span>60 秒</span></div></div><p className="help-text">演示结果由预设序列产生，不经过 GSC 模型，不代表识别性能。</p><Button variant="outline" className="full-width" onClick={()=>switchMode('real')}><Upload size={16}/> 使用自己的 EEG</Button></>:<>
 <div className={`upload-zone ${drag?'dragging':''}`} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);setFiles(Array.from(e.dataTransfer.files))}}><Upload size={25}/><strong>拖入 EEG 文件</strong><span>CSV · NPZ · SET + FDT</span><Button variant="outline" onClick={()=>uploadRef.current?.click()}>选择文件</Button><input ref={uploadRef} type="file" aria-label="选择EEG文件" accept=".csv,.npz,.set,.fdt" multiple hidden onChange={e=>setFiles(Array.from(e.target.files||[]))}/></div>{files.length>0&&<p className="file-names">{files.map(f=>f.name).join(' + ')}</p>}
 <div className="two-fields"><Field label="采样率（Hz）" id="sfreq"><Input id="sfreq" type="number" min={250} max={5000} value={sfreq} onChange={e=>setSfreq(e.target.value)}/></Field><Field label="信号单位" id="unit"><Choice id="unit" value={unit} onChange={setUnit} options={['uV','mV','V'].map(v=>({value:v,label:v==='uV'?'μV（微伏）':v}))}/></Field></div>
 <details className="form-details"><summary>手动填写刺激事件时间</summary><Label htmlFor="onsets">秒数数组（可选）</Label><Input id="onsets" placeholder="[0, 2, 4, 6]" value={onsets} onChange={e=>setOnsets(e.target.value)}/><p>填写后覆盖文件内事件。NPZ 的采样率与单位以文件元数据为准，SET 自动读取采样率。</p></details>
 <Button className="full-width" disabled={!!busy||!files.length} onClick={()=>void upload()}>{busy==='upload'?<LoaderCircle className="spin" size={16}/>:<FileUp size={16}/>} 导入并检查</Button><div className="template-links"><a href="/api/templates/example_eeg.csv" download>CSV 模板</a><a href="/api/templates/example_eeg.npz" download>NPZ 模板</a><a href="/api/templates/README.md" download>格式说明</a></div>
 <Field label="查询记录" id="query"><Choice id="query" value={query} onChange={v=>{setQuery(v);setResult(null)}} options={recOptions} placeholder="选择独立查询记录" disabled={!!busy}/></Field>{current&&<div className="record-info"><span>{current.channels.length} 通道 · {current.sfreq} Hz · {current.duration_sec.toFixed(1)} 秒</span><Button variant="ghost" size="icon" aria-label="删除当前查询记录" onClick={()=>setDeleteTarget({kind:'recordings',id:current.id,label:current.name})} disabled={!!busy}><Trash2 size={15}/></Button></div>}</>}
 </section>
 <section className="lab-card"><div className="card-heading"><h2><span>02</span> 个人校准</h2></div>{mode==='demo'?<div className="demo-calibration"><Check size={18}/><div><strong>演示档案</strong><p>仅用于说明校准后的分析流程。</p></div></div>:<>
 <Field label="选择校准档案" id="profile"><Choice id="profile" value={profile} onChange={chooseProfile} options={profileOptions} placeholder="尚未选择校准档案" disabled={!!busy}/></Field>{selectedProfile&&<div className="record-info"><span>{selectedProfile.model_version===(selectedProfile.model_id?selectedFold?.version:status?.model.version)?'模型版本匹配':'模型版本已变化，需重新校准'}</span><Button variant="ghost" size="icon" aria-label="删除校准档案" disabled={!!busy} onClick={()=>setDeleteTarget({kind:'calibrations',id:profile,label:`${selectedProfile.subject} / ${selectedProfile.session}`})}><Trash2 size={15}/></Button></div>}
 <div className="two-fields"><Field label="用户" id="subject"><Input id="subject" value={subject} maxLength={80} disabled={!!busy} onChange={e=>setSubject(e.target.value)}/></Field><Field label="采集 session" id="session"><Input id="session" value={session} maxLength={80} disabled={!!busy} onChange={e=>setSession(e.target.value)}/></Field></div>
 <Button variant="outline" className="full-width" disabled={!!busy} onClick={()=>setShowCalibration(v=>!v)}><Plus size={16}/>{showCalibration?'收起校准设置':'建立新校准档案'}</Button>
 {showCalibration&&<div className="calibration-form">{status?.model.mode==='folds'&&<Field label="目标被试对应的模型折" id="model-fold"><Choice id="model-fold" value={modelId} onChange={setModelId} options={(status.model.folds||[]).filter(f=>f.ready).map(f=>({value:f.id,label:`${f.id} · 验证 ${f.validation_subject}`}))} placeholder="请选择目标折"/><p className="help-text">论文被试 sub-XX 必须选同名留出折。新用户可指定一折试用，但原论文准确率不适用于该用户。</p></Field>}<Field label="0-back 支持记录" id="support0"><Choice id="support0" value={record0} onChange={setRecord0} options={recOptions}/></Field><Field label="2-back 支持记录" id="support2"><Choice id="support2" value={record2} onChange={setRecord2} options={recOptions}/></Field><Field label="每类支持窗口数" id="shots"><Input id="shots" type="number" min={2} max={100} value={shots} onChange={e=>setShots(e.target.value)}/></Field><p className="help-text">建议当前 session 每类 20 个窗口。与论文跨 3 个 session 的 7/7/6 分配不同，不沿用论文成绩。</p><Button className="full-width" disabled={!!busy||!status?.model.ready||!record0||!record2||(status?.model.mode==='folds'&&!modelId)||!subject.trim()||!session.trim()} onClick={()=>void createCalibration()}>{busy==='calibration'?<LoaderCircle size={16} className="spin"/>:<Layers3 size={16}/>} 保存校准</Button></div>}
 </>}
 <div className="calibration-note"><Info size={15}/><p>真实推理需要两类支持样本。标准化统计量只来自支持集，查询真值不参与更新。</p></div></section>
 <section className="lab-card"><div className="card-heading"><h2><span>03</span> 分析设置</h2></div><Field label="分窗方式" id="window-mode"><Choice id="window-mode" value={windowMode} onChange={v=>setWindowMode(v as any)} disabled={mode==='demo'||!!busy} options={[{value:'continuous',label:'连续 2 秒分窗'},{value:'events',label:'刺激事件对齐 · 2 秒'}]}/></Field>{mode==='real'&&windowMode==='events'&&<Field label="刺激事件类型（逗号分隔）" id="event-types"><Input id="event-types" placeholder={current?.event_types.join(', ')||'stimulus'} value={eventTypes} onChange={e=>setEventTypes(e.target.value)}/><p className="help-text">留空将使用所有导入事件，请确认它们都是刺激事件。</p></Field>}
 <p className="help-text">{windowMode==='continuous'?'连续切窗不等同于论文的刺激事件对齐。离线滤波完成后才执行顺序判决。':'事件超出记录或之后不足 2 秒时，将停止分析并提示修正。'}</p><div className="temporal-status"><span>时序模块</span><strong>{mode==='demo'?'预设演示':selectedProfile?.model_id?selectedFold?.temporal_ready?'已配置 · 独立验证':'未启用':status?.model.temporal_ready?'已配置':'未启用'}</strong></div><Button className="full-width analyze-btn" disabled={!!busy||!ready} onClick={()=>void run()}>{busy==='analysis'||busy==='demo'?<LoaderCircle className="spin" size={17}/>:<Play size={17}/>} {busy==='analysis'?'正在分析':busy==='demo'?'正在回放演示':mode==='demo'?'运行演示':'开始分析'}</Button>{mode==='real'&&!status?.model.ready&&<p className="help-text amber">需先接入训练权重。上传与信号预览仍可使用。</p>}</section>
 </aside><div className="lab-main"><section className="lab-card signal-panel"><div className="card-heading"><div><p className="eyebrow">SIGNAL OVERVIEW</p><h2>信号预览</h2></div><span className="small-pill">{mode==='demo'?'合成信号':current?'原始信号 · μV':'等待输入'}</span></div>{mode==='demo'||current?<><div className="wave-legend">{['Fp1','Fz','C3','Pz','O1'].map((ch,i)=><span key={ch}><i style={{background:['#84e4c6','#83b8dc','#b9b2e2','#dcc399','#889ca9'][i]}}/>{ch}</span>)}<small>通道纵向偏移；提示数值含偏移，仅供形态预览</small></div><SignalChart data={mode==='demo'?demoWave:current?.preview||[]}/><div className="signal-meta"><span>{mode==='demo'?'60.0':current?.duration_sec.toFixed(1)} <small>秒</small></span><span>{mode==='demo'?'250':current?.sfreq} <small>Hz</small></span><span>62 <small>通道</small></span><span>5 <small>预览通道 · 分箱均值</small></span></div>{mode==='real'&&current&&<details className="metadata-details"><summary>查看通道与事件信息</summary><p>{current.channels.join(' · ')}</p><p>刺激事件：{current.events.length} 个 · 类型：{current.event_types.join(', ')||'无'}</p>{!!current.extra_channels_ignored?.length&&<p>已忽略辅助通道：{current.extra_channels_ignored.join(', ')}</p>}<p>已按名称对齐全部 62 通道，原始单位 {current.original_unit}，换算为 μV。请确认这段记录属于所选用户与 session。</p></details>}</>:<div className="empty-state"><Waves size={42}/><h3>从导入一段 EEG 开始</h3><p>先检查采样率、通道和信号形态，<br/>再进入个人校准与分析。</p></div>}</section>
 <section className="lab-card result-panel"><div className="card-heading"><div><p className="eyebrow">WORKLOAD INFERENCE</p><h2>工作负荷结果</h2></div>{done&&<div className="export-actions"><Button variant="outline" size="sm" onClick={()=>result.mode==='demo'?downloadDemo(result,'csv'):window.open(`/api/analyses/${result.id}/export?format=csv`,'_self')}><Download size={14}/> CSV</Button><Button variant="outline" size="sm" onClick={()=>result.mode==='demo'?downloadDemo(result,'json'):window.open(`/api/analyses/${result.id}/export?format=json`,'_self')}>JSON</Button></div>}</div>
 {result&&['running','queued'].includes(result.status)?<div className="processing"><LoaderCircle size={30} className="spin"/><h3>{mode==='demo'?'正在回放预设演示':'正在处理脑电记录'}</h3><Progress value={result.progress}/><p>{mode==='demo'?'演示不会调用真实模型。':'预处理 → Welch 频谱 → GSC 特征 → 原型分类'}</p></div>:done&&result.rows?<>
 {result.mode==='demo'&&<div className="demo-result-banner"><FlaskConical size={16}/> 以下为预设演示结果，不是网络实际预测。</div>}
 <div className="result-metrics"><div><span>分析窗口</span><strong>{result.windows}<small>个</small></strong></div><div><span>2-back 判决占比</span><strong>{((result.high_ratio||0)*100).toFixed(1)}<small>%</small></strong></div><div><span>状态切换</span><strong>{result.switches}<small>次</small></strong></div></div>
 <div className="timeline-label"><h3>状态时间线</h3><span><i className="low"/> 0-back <i className="high"/> 2-back</span></div><div className="state-timeline" aria-label="逐窗状态时间线">{result.rows.map(r=><div key={r.window} className={r.class_label===2?'high':'low'} title={`${r.start_sec}–${r.end_sec}s · ${r.class_label}-back`}/>)}</div><div className="timeline-ticks"><span>{result.rows[0].start_sec}s</span><span>{result.rows[result.rows.length-1].end_sec}s</span></div>
 <ChartContainer config={{prob_0:{label:'0-back 概率',color:'#85e5c6'},prob_2:{label:'2-back 概率',color:'#85b7eb'},state_prob_2:{label:'2-back 状态概率',color:'#dec694'}}} className="probability-chart"><LineChart data={result.rows} margin={{left:-15,right:12,top:10,bottom:0}}><CartesianGrid stroke="#253038" vertical={false}/><XAxis dataKey="start_sec" tickFormatter={v=>`${v}s`} minTickGap={40}/><YAxis domain={[0,1]} ticks={[0,.5,1]} tickFormatter={v=>`${Math.round(v*100)}%`}/><Tooltip contentStyle={{background:'#192127',border:'1px solid #394952',borderRadius:8}} formatter={(v:any)=>`${(Number(v)*100).toFixed(1)}%`} labelFormatter={v=>`${v} 秒`}/><Line dataKey="prob_0" name="0-back 概率" stroke="#85e5c6" dot={false} strokeWidth={2} isAnimationActive={false}/><Line dataKey="prob_2" name="2-back 概率" stroke="#85b7eb" dot={false} strokeWidth={2} isAnimationActive={false}/>{result.temporal_enabled&&<Line dataKey="state_prob_2" name="2-back 状态概率" stroke="#dec694" dot={false} strokeDasharray="5 4" strokeWidth={1.5} isAnimationActive={false}/>}</LineChart></ChartContainer>
 <div className="prob-legend"><span style={{color:'#85e5c6'}}>— 0-back 概率</span><span style={{color:'#85b7eb'}}>— 2-back 概率</span>{result.temporal_enabled&&<span style={{color:'#dec694'}}>┄ 2-back 状态概率</span>}</div><p className="help-text">模型概率未经临床置信度校准。{result.temporal_enabled?result.mode==='demo'?'本次展示预设的时序结果。':'本次使用时序模块。':'本次未启用时序模块，最终判决来自原型分类。'}</p>
 <details className="window-details"><summary>逐窗数据与处理信息</summary><div className="table-scroll"><table><thead><tr><th>窗口</th><th>起始时间</th><th>P(0-back)</th><th>P(2-back)</th><th>判决</th></tr></thead><tbody>{result.rows.slice(page*20,(page+1)*20).map(r=><tr key={r.window}><td>{r.window}</td><td>{r.start_sec.toFixed(2)}s</td><td>{(r.prob_0*100).toFixed(1)}%</td><td>{(r.prob_2*100).toFixed(1)}%</td><td>{r.class_label}-back</td></tr>)}</tbody></table></div><div className="table-pagination"><Button variant="ghost" size="sm" disabled={page===0} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={16}/>上一页</Button><span>{page+1} / {Math.ceil(result.rows.length/20)}</span><Button variant="ghost" size="sm" disabled={(page+1)*20>=result.rows.length} onClick={()=>setPage(p=>p+1)}>下一页<ChevronRight size={16}/></Button></div><p className="help-text">{result.recording_name} · {result.mode==='demo'?'演示结果':'独立查询记录'} · 2 秒 / 窗口</p>{result.audit&&<div className="processing-audit"><p>分窗：{result.audit.window_mode==='events'?'刺激事件对齐':'连续 2 秒'} · 舍弃尾部：{result.audit.discarded_tail_sec} 秒</p><p>坏导修复：{result.audit.bad_channels_repaired.join('、')||'无'} · 离线双向滤波</p><p>模型版本：{result.model_version?.slice(0,16)} · 初始状态来自保存的校准档案</p></div>}</details>
 </>:<div className="empty-state result-empty"><div className="empty-orbit"><Activity size={35}/></div><h3>{result?.status==='failed'?'这次分析未能完成':'等待一次分析'}</h3><p>{mode==='demo'?'点击“运行演示”，查看预设时间线与概率曲线。':'导入查询记录并选择匹配的个人校准档案后开始。'}</p>{result?.error&&<p className="amber">{result.error}</p>}</div>}
 </section>
 {mode==='real'&&<section className="lab-card"><div className="card-heading"><h2>本地记录与分析</h2><span className="small-pill">{records.length} 条信号 · {history.length} 次分析</span></div>{records.length===0&&history.length===0?<p className="help-text">上传与分析记录会显示在这里，可随时删除。</p>:<div className="history-list">{records.map(r=><div key={r.id}><Waves size={17}/><button onClick={()=>setQuery(r.id)}><strong>{r.name}</strong><small>{r.duration_sec.toFixed(1)} 秒 · {r.sfreq} Hz</small></button><Button variant="ghost" size="icon" aria-label={`删除信号 ${r.name}`} disabled={!!busy} onClick={()=>setDeleteTarget({kind:'recordings',id:r.id,label:r.name})}><Trash2 size={15}/></Button></div>)}{history.map(h=><div key={h.id}><Activity size={17}/><button onClick={()=>{api<Result>(`/analyses/${h.id}`).then(v=>{setResult(v);setPage(0)}).catch(e=>setError(e.message))}}><strong>{h.recording_name||'分析记录'}</strong><small>{h.status==='complete'?'已完成':h.status==='failed'?'未完成':'处理中'} · {new Date((h.created_at||0)*1000).toLocaleString('zh-CN')}</small></button><Button variant="ghost" size="icon" aria-label="删除分析结果" disabled={!!busy||['queued','running'].includes(h.status)} onClick={()=>setDeleteTarget({kind:'analyses',id:h.id,label:'这次分析结果'})}><Trash2 size={15}/></Button></div>)}</div>}</section>}
 <div className="model-note"><ShieldCheck size={20}/><div><strong>{mode==='demo'?'演示与真实分析严格分开':status?.model.label||'等待本地服务'}</strong><p>{mode==='demo'?'演示数据不会写入真实记录，不用于校准或计算研究指标。':status?.model.message||'请启动后端服务后刷新状态。'}</p></div></div>
 </div></div>
 <AlertDialog open={!!deleteTarget} onOpenChange={open=>{if(!open)setDeleteTarget(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>删除本机记录？</AlertDialogTitle><AlertDialogDescription>将删除“{deleteTarget?.label}”。被校准档案引用或正在分析的记录无法删除。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>取消</AlertDialogCancel><AlertDialogAction onClick={()=>void performDelete()}>删除</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>
}
